---
version: 0.2


phases:
  install:
    commands:
      - curl -sS -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/aws-iam-authenticator
      - curl -sS -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/kubectl
      - chmod +x ./kubectl ./aws-iam-authenticator
      - export PATH=$PWD/:$PATH
      - apt-get update && apt-get -y install jq python3-pip python3-dev && pip3 install --upgrade awscli
  pre_build:
      commands:
        - TAG="$REPOSITORY_NAME.$REPOSITORY_BRANCH.$ENVIRONMENT_NAME.$(date +%Y-%m-%d.%H.%M.%S).$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
        - sed -i 's@CONTAINER_IMAGE@'"$REPOSITORY_URI:$TAG"'@' simple_jwt_api.yml
        - $(aws ecr get-login --no-include-email)
        - export KUBECONFIG=$HOME/.kube/config
  build:
    commands:
      - docker build --tag $REPOSITORY_URI:$TAG .

  post_build:
    commands:
      - docker push $REPOSITORY_URI:$TAG
      - export AWS_ACCESS_KEY_ID="ASIAZVG4NP5DJLGW7VHL"
      - export AWS_SECRET_ACCESS_KEY="2K/t0jsRQnMl2pzJeAVR0yWP9zYjMvoF6ritCqXj"
      - export AWS_SESSION_TOKEN="FwoGZXIvYXdzECQaDIKopm1oBwhyyJDDESLHAfb2tos7VO9zjgM3DJbckhz0QVwhXF1FJ+cbMcjoSzJL490RaoaoXJvBGZb6+EJbhYBuiFtSQnoDBVZm5FBx//lXNksQFRV368r+8OlfMRzg4Rr2s0RpuB0MJSfNtBffXYZLgjYvR1DqWpEAHhr5Efo0UAgvpBQPk3UqaqP8Z04G/rAUhpziLcwZqD920ganRQ4FDtbXmCUpV8jOz9AdGAZMp0V31wpOnMQb9dP1nEBcB5sP99iluGBfZfnNSctcD47qXIyBXnMomr2n9gUyLZc50JbG0fOWlbUFajDAIYXB/qJjKyvyiarAt/vNVp13jLFRa8UYYCc7d/hBrA=="
      - export AWS_EXPIRATION=2020-05-23T22:40:25-0700
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME
      - kubectl apply -f simple_jwt_api.yml
      - printf '[{"name":"simple_jwt_api","imageUri":"%s"}]' $REPOSITORY_URI:$TAG > build.json
      - pwd
      - ls
artifacts:
  files: build.json