---
version: 0.2


phases:
  install:
    commands:
      - curl -sS -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/aws-iam-authenticator
      - curl -sS -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/kubectl
      - chmod +x ./kubectl ./aws-iam-authenticator
      - export PATH=$PWD/:$PATH
      - apt-get update && apt-get -y install jq python3-pip python3-dev && pip3 install --upgrade awscli
  pre_build:
      commands:
        - TAG="$REPOSITORY_NAME.$REPOSITORY_BRANCH.$ENVIRONMENT_NAME.$(date +%Y-%m-%d.%H.%M.%S).$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
        - sed -i 's@CONTAINER_IMAGE@'"$REPOSITORY_URI:$TAG"'@' simple_jwt_api.yml
        - $(aws ecr get-login --no-include-email)
        - export KUBECONFIG=$HOME/.kube/config
        - python3 -m pip install --upgrade pip
        - python3 -m pip install -r requirements.txt
        - python3 -m pytest test_main.py
  build:
    commands:
      - docker build --tag $REPOSITORY_URI:$TAG .

  post_build:
    commands:
      - docker push $REPOSITORY_URI:$TAG
      - export AWS_ACCESS_KEY_ID="ASIAZVG4NP5DHABPM7ON"
      - export AWS_SECRET_ACCESS_KEY="O4bajXsF0Pzf9F6vblJWNFk31x0tE3pLvybNzag6"
      - export AWS_SESSION_TOKEN="FwoGZXIvYXdzECYaDHet8vaDiVjogtKBKSLHAZJ1IGalmSwZOCSc+neMJRaquH4eIPT41qIGZdrJ7VU6VuTHPIEXVAt8PpHvWAjNPu4ALnogrkC7knC8AZP/rOE6eaNUWZicSxliWpTMeMASPh1H+aMdpXMjWhDp5d0HffHceC7iLQMqCFco0c9IYz+jj81RjuOX/FM10He5X7oGusSGGf8wFrx3RnJbAk5s+LC44wXDKgzGp3lKFaKatYZAxlfwsvBVQQt47XqOnaIdFo7CLGwV6K1BBiVnTeAAq2aUPjRaSs4oweWn9gUyLe22bF1L6Dn5vPYjUUhgpRJR2q0xYCwLiReB3nK/0SyRCdHHPOgCE+UEGmNq7w=="
      - export AWS_EXPIRATION=2020-05-24T00:06:24-0700
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME
      - kubectl apply -f simple_jwt_api.yml
      - printf '[{"name":"simple_jwt_api","imageUri":"%s"}]' $REPOSITORY_URI:$TAG > build.json
      - pwd
      - ls
artifacts:
  files: build.json